# Generated by Django 4.2.13 on 2024-06-18 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('likes', models.ManyToManyField(to='core_application.profile')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_application.post')),
            ],
            options={
                'verbose_name_plural': 'Likes',
            },
        ),
    ]
